//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutomatedTaskSchedulingSystem.DataAccess.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ATSSEntities : DbContext
    {
        public ATSSEntities()
            : base("name=ATSSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblSetupLoc> tblSetupLoc { get; set; }
        public virtual DbSet<tblSetupOrg> tblSetupOrg { get; set; }
        public virtual DbSet<tblSetupPostion> tblSetupPostion { get; set; }
        public virtual DbSet<tblSetupSysUser> tblSetupSysUser { get; set; }
        public virtual DbSet<tblConfig> tblConfig { get; set; }
        public virtual DbSet<tblEmployee> tblEmployee { get; set; }
        public virtual DbSet<tblEmployeeeTemp> tblEmployeeeTemp { get; set; }
        public virtual DbSet<tblEmployeeAvail> tblEmployeeAvail { get; set; }
        public virtual DbSet<tblSchedule> tblSchedule { get; set; }
        public virtual DbSet<tblSetupTask> tblSetupTask { get; set; }
    }
}
