//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutomatedTaskSchedulingSystem.DataAccess.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSchedule
    {
        public int SchID { get; set; }
        public System.DateTime SchDate { get; set; }
        public string Location { get; set; }
        public string Task { get; set; }
        public string Name { get; set; }
    }
}
